import { PROVIDER_REGISTRY, providerOf } from "@modelgov/policy-engine";

// Concrete LiteLLM target + provider key env for known built-in model strings.
const LITELLM_MAP: Record<string, { model: string; keyEnv?: string; apiBase?: string }> = {
  "openai/gpt-4o-mini": { model: "openai/gpt-4o-mini", keyEnv: "OPENAI_API_KEY" },
  "openai/gpt-4o": { model: "openai/gpt-4o", keyEnv: "OPENAI_API_KEY" },
  "openai/gpt-5": { model: "openai/gpt-4o", keyEnv: "OPENAI_API_KEY" },
  "anthropic/claude-haiku": { model: "anthropic/claude-3-5-haiku-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "anthropic/claude-sonnet": { model: "anthropic/claude-3-5-sonnet-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "anthropic/claude-opus": { model: "anthropic/claude-3-opus-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "gemini/gemini-flash": { model: "gemini/gemini-1.5-flash", keyEnv: "GEMINI_API_KEY" },
  "gemini/gemini-pro": { model: "gemini/gemini-1.5-pro", keyEnv: "GEMINI_API_KEY" },
  "gemini/gemini-ultra": { model: "gemini/gemini-1.5-pro", keyEnv: "GEMINI_API_KEY" },
  "ollama/llama3.2:3b": { model: "ollama/llama3.2:3b", apiBase: "http://host.docker.internal:11434" },
};

function litellmParamsFor(m: string): string[] {
  const map = LITELLM_MAP[m];
  if (map) {
    const params = [`      model: ${map.model}`];
    if (map.keyEnv) params.push(`      api_key: os.environ/${map.keyEnv}`);
    if (map.apiBase) params.push(`      api_base: ${map.apiBase}`);
    return params;
  }
  if (m.startsWith("azure_ai/")) {
    return [
      `      model: ${m}`,
      `      api_key: os.environ/AZURE_AI_API_KEY`,
      `      api_base: os.environ/AZURE_AI_API_BASE`,
    ];
  }
  if (m.startsWith("azure/")) {
    return [
      `      model: ${m}`,
      `      api_key: os.environ/AZURE_API_KEY`,
      `      api_base: os.environ/AZURE_API_BASE`,
      `      api_version: os.environ/AZURE_API_VERSION`,
    ];
  }
  const spec = PROVIDER_REGISTRY[providerOf(m)];
  switch (spec?.authKind) {
    case "aws":
      return [
        `      model: ${m}`,
        `      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID`,
        `      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY`,
        `      aws_region_name: os.environ/AWS_REGION_NAME`,
      ];
    case "gcp":
      return [
        `      model: ${m}`,
        `      vertex_project: os.environ/VERTEX_PROJECT`,
        `      vertex_location: os.environ/VERTEX_LOCATION`,
      ];
    case "oauth_device":
      return [`      model: ${m}`];
    case "api_key":
      return [`      model: ${m}`, `      api_key: os.environ/${spec.credentialEnvVars[0]}`];
    default:
      return [`      model: ${m}`];
  }
}

/** Build litellm_config.yaml for the model strings a policy uses. */
export function renderLitellmConfig(models: string[]): string {
  const entries = models.map((m) => `  - model_name: ${m}\n    litellm_params:\n${litellmParamsFor(m).join("\n")}`);
  return `# Generated by create-modelgov. model_name must match modelgov.yaml model_classes.
model_list:
${entries.join("\n")}

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
`;
}
