import { PROVIDER_REGISTRY, providerOf } from "@modelgov/policy-engine";

// Concrete LiteLLM target + provider key env for known built-in model strings.
const LITELLM_MAP: Record<string, { model: string; keyEnv?: string; apiBase?: string }> = {
  "openai/gpt-4o-mini": { model: "openai/gpt-4o-mini", keyEnv: "OPENAI_API_KEY" },
  "openai/gpt-4o": { model: "openai/gpt-4o", keyEnv: "OPENAI_API_KEY" },
  "openai/gpt-5": { model: "openai/gpt-5", keyEnv: "OPENAI_API_KEY" },
  "anthropic/claude-haiku": { model: "anthropic/claude-3-5-haiku-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "anthropic/claude-sonnet": { model: "anthropic/claude-3-5-sonnet-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "anthropic/claude-opus": { model: "anthropic/claude-3-opus-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "gemini/gemini-flash": { model: "gemini/gemini-2.5-flash", keyEnv: "GEMINI_API_KEY" },
  "gemini/gemini-flash-lite": { model: "gemini/gemini-2.0-flash-lite", keyEnv: "GEMINI_API_KEY" },
  "gemini/gemini-pro": { model: "gemini/gemini-2.5-pro", keyEnv: "GEMINI_API_KEY" },
  // Legacy alias (no longer a default tier) → real top model, kept for back-compat.
  "gemini/gemini-ultra": { model: "gemini/gemini-2.5-pro", keyEnv: "GEMINI_API_KEY" },
  "ollama/llama3.2:3b": { model: "ollama/llama3.2:3b", apiBase: "http://host.docker.internal:11434" },
};

function litellmParamsFor(m: string): string[] {
  const map = LITELLM_MAP[m];
  if (map) {
    const params = [`      model: ${map.model}`];
    if (map.keyEnv) params.push(`      api_key: os.environ/${map.keyEnv}`);
    if (map.apiBase) params.push(`      api_base: ${map.apiBase}`);
    return params;
  }
  if (m.startsWith("azure_ai/")) {
    return [
      `      model: ${m}`,
      `      api_key: os.environ/AZURE_AI_API_KEY`,
      `      api_base: os.environ/AZURE_AI_API_BASE`,
    ];
  }
  if (m.startsWith("azure/")) {
    return [
      `      model: ${m}`,
      `      api_key: os.environ/AZURE_API_KEY`,
      `      api_base: os.environ/AZURE_API_BASE`,
      `      api_version: os.environ/AZURE_API_VERSION`,
    ];
  }
  const spec = PROVIDER_REGISTRY[providerOf(m)];
  switch (spec?.authKind) {
    case "aws":
      // Let boto's default credential chain read AWS_ACCESS_KEY_ID /
      // AWS_SECRET_ACCESS_KEY / AWS_SESSION_TOKEN from the environment (all are
      // passed to the litellm container). Passing static keys explicitly makes
      // boto ignore the ambient STS session token, which breaks temporary
      // (ASIA…) credentials; only the region needs to be named for LiteLLM.
      return [
        `      model: ${m}`,
        `      aws_region_name: os.environ/AWS_REGION_NAME`,
      ];
    case "gcp":
      return [
        `      model: ${m}`,
        `      vertex_project: os.environ/VERTEX_PROJECT`,
        `      vertex_location: os.environ/VERTEX_LOCATION`,
      ];
    case "oauth_device":
      return [`      model: ${m}`];
    case "api_key":
      return [`      model: ${m}`, `      api_key: os.environ/${spec.credentialEnvVars[0]}`];
    default:
      return [`      model: ${m}`];
  }
}

/**
 * Model string used for hybrid injection screening (routes to demo-llm locally).
 * Deliberately a `local/` sentinel — NOT a real provider model like
 * `openai/gpt-4o-mini` — so it never collides with the user's own cheap-tier
 * model. (A collision would silently route real chat traffic to the demo.)
 * The `local/` prefix also makes it pricing-exempt (see isPricingExemptModel).
 */
export const HYBRID_INJECTION_MODEL = "local/injection-guard";

const DEMO_LITELLM_PARAMS = `      model: openai/modelgov-demo
      api_base: http://demo-llm:8080/v1
      api_key: demo-key`;

/** Build litellm_config.yaml for the model strings a policy uses. */
export function renderLitellmConfig(
  models: string[],
  opts?: { hybridInjection?: boolean },
): string {
  const names = [...models];
  if (opts?.hybridInjection && !names.includes(HYBRID_INJECTION_MODEL)) {
    names.push(HYBRID_INJECTION_MODEL);
  }
  const entries = names.map((m) => {
    if (opts?.hybridInjection && m === HYBRID_INJECTION_MODEL) {
      return `  - model_name: ${m}\n    litellm_params:\n${DEMO_LITELLM_PARAMS}`;
    }
    return `  - model_name: ${m}\n    litellm_params:\n${litellmParamsFor(m).join("\n")}`;
  });
  const hybridNote = opts?.hybridInjection
    ? `# Hybrid injection: ${HYBRID_INJECTION_MODEL} routes to demo-llm so injection\n# screening does not consume cloud free-tier quota (and never shadows a real model).\n`
    : "";
  return `${hybridNote}# Generated by create-modelgov. model_name must match modelgov.yaml model_classes.
model_list:
${entries.join("\n")}

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
`;
}
