import { PROVIDER_REGISTRY, providerOf } from "@modelgov/policy-engine";
import { adapterFor, type Framework } from "./adapters";
import {
  composeFileFor,
  modelStringsFor,
  renderModelgovYaml,
  renderEnv,
  type ScaffoldOptions,
} from "./render";

export interface ProjectOptions extends ScaffoldOptions {
  framework: Framework;
}

// Concrete LiteLLM target + provider key env for known built-in model strings.
const LITELLM_MAP: Record<string, { model: string; keyEnv?: string; apiBase?: string }> = {
  "openai/gpt-4o-mini": { model: "openai/gpt-4o-mini", keyEnv: "OPENAI_API_KEY" },
  "openai/gpt-4o": { model: "openai/gpt-4o", keyEnv: "OPENAI_API_KEY" },
  "openai/gpt-5": { model: "openai/gpt-4o", keyEnv: "OPENAI_API_KEY" }, // stand-in until available
  "anthropic/claude-haiku": { model: "anthropic/claude-3-5-haiku-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "anthropic/claude-sonnet": { model: "anthropic/claude-3-5-sonnet-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "anthropic/claude-opus": { model: "anthropic/claude-3-opus-latest", keyEnv: "ANTHROPIC_API_KEY" },
  "gemini/gemini-flash": { model: "gemini/gemini-1.5-flash", keyEnv: "GEMINI_API_KEY" },
  "gemini/gemini-pro": { model: "gemini/gemini-1.5-pro", keyEnv: "GEMINI_API_KEY" },
  "gemini/gemini-ultra": { model: "gemini/gemini-1.5-pro", keyEnv: "GEMINI_API_KEY" }, // stand-in
  "ollama/llama3.2:3b": { model: "ollama/llama3.2:3b", apiBase: "http://host.docker.internal:11434" },
};

// Pin to a digest in production; override via MODELGOV_API_IMAGE in .env.
const DEFAULT_API_IMAGE = "ghcr.io/mml555/modelgov/modelgov-api:latest";

/** LiteLLM params for a model string — derives provider wiring from the registry. */
function litellmParamsFor(m: string): string[] {
  // Built-in friendly names are remapped to real LiteLLM model ids (+ apiBase for
  // Ollama); check this first so the remap wins over prefix dispatch.
  const map = LITELLM_MAP[m];
  if (map) {
    const params = [`      model: ${map.model}`];
    if (map.keyEnv) params.push(`      api_key: os.environ/${map.keyEnv}`);
    if (map.apiBase) params.push(`      api_base: ${map.apiBase}`);
    return params;
  }
  // Azure variants are api_key-based but need the endpoint (+ version) too.
  if (m.startsWith("azure_ai/")) {
    // Azure AI Foundry — model name is your deployment; needs the Foundry endpoint.
    return [
      `      model: ${m}`,
      `      api_key: os.environ/AZURE_AI_API_KEY`,
      `      api_base: os.environ/AZURE_AI_API_BASE`,
    ];
  }
  if (m.startsWith("azure/")) {
    // azure/<deployment> — needs endpoint + api version alongside the key.
    return [
      `      model: ${m}`,
      `      api_key: os.environ/AZURE_API_KEY`,
      `      api_base: os.environ/AZURE_API_BASE`,
      `      api_version: os.environ/AZURE_API_VERSION`,
    ];
  }
  const spec = PROVIDER_REGISTRY[providerOf(m)];
  switch (spec?.authKind) {
    case "aws":
      // Bedrock — LiteLLM signs requests with AWS credentials from the env.
      return [
        `      model: ${m}`,
        `      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID`,
        `      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY`,
        `      aws_region_name: os.environ/AWS_REGION_NAME`,
      ];
    case "gcp":
      // Vertex — GOOGLE_APPLICATION_CREDENTIALS is read from the env by the SDK.
      return [
        `      model: ${m}`,
        `      vertex_project: os.environ/VERTEX_PROJECT`,
        `      vertex_location: os.environ/VERTEX_LOCATION`,
      ];
    case "oauth_device":
      // GitHub Copilot — LiteLLM performs the OAuth device flow and caches the token.
      return [`      model: ${m}`];
    case "api_key":
      // OpenRouter, Mistral, Groq, xAI, DeepSeek, Cohere, …
      return [`      model: ${m}`, `      api_key: os.environ/${spec.credentialEnvVars[0]}`];
    default:
      return [`      model: ${m}`];
  }
}

function renderLitellmConfig(models: string[]): string {
  const entries = models.map((m) => `  - model_name: ${m}\n    litellm_params:\n${litellmParamsFor(m).join("\n")}`);
  return `# Generated by create-modelgov. model_name must match modelgov.yaml model_classes.
model_list:
${entries.join("\n")}

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
`;
}

function renderCompose(opts: ProjectOptions): string {
  const localOnly = opts.template.localOnly === true;
  const withPresidio = !localOnly && opts.safetyPreset !== "dev";
  const presidioServices = withPresidio
    ? `
  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports: ["127.0.0.1:5002:3000"]
  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports: ["127.0.0.1:5001:3000"]`
    : "";
  const presidioEnv = withPresidio
    ? `
      PRESIDIO_ANALYZER_URL: http://presidio-analyzer:3000
      PRESIDIO_ANONYMIZER_URL: http://presidio-anonymizer:3000`
    : "";
  const presidioDeps = withPresidio
    ? `
      presidio-analyzer:
        condition: service_started
      presidio-anonymizer:
        condition: service_started`
    : "";

  return `# Generated by create-modelgov. \`docker compose up -d\` to run the gateway.
# NOTE: set the api image below to your published Modelgov API image.
name: ${opts.projectName}

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modelgov
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 12
    volumes: [pgdata:/var/lib/postgresql/data]

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    env_file: [.env]
    volumes: ["./litellm_config.yaml:/app/config.yaml:ro"]
${presidioServices}

  api:
    image: \${MODELGOV_API_IMAGE:-${DEFAULT_API_IMAGE}}
    depends_on:
      postgres:
        condition: service_healthy
      litellm:
        condition: service_started${presidioDeps}
    env_file: [.env]
    environment:
      MODELGOV_CONFIG: /app/modelgov.yaml${presidioEnv}
    volumes: ["./modelgov.yaml:/app/modelgov.yaml:ro"]
    ports: ["127.0.0.1:3000:3000"]

volumes:
  pgdata:
`;
}

function renderSmokeMjs(opts: ProjectOptions): string {
  const t = opts.template;
  return `// One-command smoke test: sends a single guarded request through Modelgov.
//   node scripts/smoke.mjs
const url = process.env.MODELGOV_URL ?? "http://localhost:3000";
const key = process.env.MODELGOV_API_KEY ?? "sk-modelgov-api-local";
const res = await fetch(new URL("/v1/chat", url), {
  method: "POST",
  headers: { "content-type": "application/json", authorization: \`Bearer \${key}\` },
  body: JSON.stringify({
    userId: "smoke",
    userType: "${t.exampleUserType}",
    feature: "${t.primaryFeature}",
    messages: [{ role: "user", content: ${JSON.stringify(t.examplePrompt)} }],
  }),
});
const body = await res.json().catch(() => ({}));
console.log(res.status, JSON.stringify(body, null, 2));
process.exit(res.ok ? 0 : 1);
`;
}

function renderReadme(opts: ProjectOptions, files: string[]): string {
  const t = opts.template;
  const adapter = adapterFor(opts.framework, t);
  return `# ${opts.projectName}

Modelgov scaffold — template \`${t.id}\`, framework \`${opts.framework}\`.

> ${t.description}

## Five-minute setup

1. **Set your provider key** in \`.env\`${t.localOnly ? " (local template uses Ollama — no cloud key needed)" : ""}.
2. **Start the gateway:** \`docker compose up -d\` (set the \`api\` image in \`docker-compose.yml\` to your published Modelgov image first).
3. **Smoke test:** \`node scripts/smoke.mjs\` → prints a \`requestId\` on success.
${adapter.installHint ? `4. **Wire your app:** \`${adapter.installHint}\`, then call the generated example route.` : ""}

## The boundary

\`\`\`text
Your app  → who is the user + may they do this? (auth, RBAC)
Modelgov  → is this AI call allowed? (budget, model access, safety)
\`\`\`

Every call declares \`userId\`, \`userType\`, and \`feature: "${t.primaryFeature}"\`.

## Generated files

${files.map((f) => `- \`${f}\``).join("\n")}

## Operate

- \`modelgov requests show <id>\` — inspect a decision
- \`modelgov usage summary\` — spend by feature/user
- Edit \`modelgov.yaml\` to change budgets, model access, or safety.
`;
}

/** Compose the full scaffold as a path → content map (no filesystem I/O). */
export function buildScaffold(opts: ProjectOptions): Map<string, string> {
  const files = new Map<string, string>();
  files.set("modelgov.yaml", renderModelgovYaml(opts));
  files.set(".env", renderEnv(opts));
  files.set("docker-compose.yml", renderCompose(opts));
  files.set("litellm_config.yaml", renderLitellmConfig(modelStringsFor(opts)));
  files.set("scripts/smoke.mjs", renderSmokeMjs(opts));

  for (const [path, content] of Object.entries(adapterFor(opts.framework, opts.template).files)) {
    files.set(path, content);
  }

  files.set("README.md", renderReadme(opts, [...files.keys()].sort()));
  return files;
}

export { composeFileFor };
