/**
 * Reads ai-guard.yaml and emits TypeScript unions for feature / user_type /
 * model_class names so the SDK enforces registered identifiers at compile time.
 *
 * Usage: pnpm generate-sdk-types
 * Env:   AI_GUARD_CONFIG (optional path to yaml; defaults to repo root)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseConfig } from "../packages/policy-engine/src/index.ts";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const configPath = resolve(
  process.env.AI_GUARD_CONFIG ?? resolve(ROOT, "ai-guard.yaml"),
);
const outPath = resolve(
  ROOT,
  "packages/sdk-typescript/src/generated/config-types.ts",
);

function unionType(name: string, values: readonly string[]): string {
  if (values.length === 0) {
    return `export type ${name} = string;`;
  }
  // Widen the union with `(string & {})` so the published SDK also accepts
  // identifiers from a CONSUMER's own ai-guard.yaml — a closed union baked from
  // this repo's config would make the package a compile error for anyone else.
  // TypeScript keeps the string literals as editor autocomplete, and the API
  // still rejects unregistered identifiers at runtime. Regenerate against your
  // own config (AI_GUARD_CONFIG=... pnpm generate-sdk-types) for tailored hints.
  const members = [...values.map((v) => JSON.stringify(v)), "(string & {})"].join(" | ");
  return `export type ${name} = ${members};`;
}

function main(): void {
  const yaml = readFileSync(configPath, "utf8");
  const config = parseConfig(yaml);

  const features = Object.keys(config.features).sort();
  const userTypes = Object.keys(config.budgets.byUserType).sort();
  const modelClasses = Object.keys(config.modelClasses).sort();

  const relConfig = configPath.startsWith(ROOT)
    ? configPath.slice(ROOT.length + 1)
    : configPath;

  const content = `// Generated by scripts/generate-sdk-types.ts — do not edit.
// Source: ${relConfig}
// Regenerate: pnpm generate-sdk-types

${unionType("FeatureName", features)}

${unionType("UserTypeName", userTypes)}

${unionType("ModelClassName", modelClasses)}
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, content);
  console.log(
    `Wrote ${outPath} (${features.length} features, ${userTypes.length} user types, ${modelClasses.length} model classes)`,
  );
}

main();
