import { writeFileSync } from "node:fs";
import { parseConfigObject } from "@modelgov/policy-engine";
import { buildServer } from "./server";
import { NoopObservability } from "./services/observability";
import { NoopGuard } from "./services/safety";

// The spec is generated by booting the real server and reading @fastify/swagger's
// view of the registered routes — the same document the live /openapi.json
// serves. No route is ever hand-listed here.
//
// Config values are irrelevant to the spec (only which routes register matters).
// A keyResolver stub is supplied so the admin routes (keys/audit/governance/
// policy) — which register only when a resolver is present — are included.
const config = parseConfigObject({
  project: { name: "openapi", environment: "production" },
  budgets: {
    global: { monthly_usd: 1, hard_stop_at_percent: 100 },
    by_user_type: { logged_in: { daily_usd: 1, daily_requests: 1, models: ["cheap"] } },
  },
  features: { support_chat: { safety: "dev", model_class: "cheap", max_tokens: 100 } },
  model_classes: { cheap: { primary: "openai/gpt-4o-mini" } },
  safety: { preset: "dev" },
});

async function main(): Promise<void> {
  const app = buildServer({
    config,
    pool: { query: async () => ({ rows: [], rowCount: 0 }) } as never,
    litellm: { chat: async () => ({ content: "", model: "", actualCostUsd: 0, raw: {} }) },
    safety: new NoopGuard(),
    observability: new NoopObservability(),
    logger: false,
    // No auth needed to enumerate routes; keyResolver makes the admin routes register.
    allowUnauthenticated: true,
    keyResolver: { resolve: async () => null, clear: () => {} },
  });

  await app.ready();
  const spec = app.swagger();
  writeFileSync("openapi.json", `${JSON.stringify(spec, null, 2)}\n`);
  await app.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
