apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelgov.fullname" . }}
  labels:
    {{- include "modelgov.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "modelgov.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
